apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-cv-app-deployment
  labels:
    app: portfolio-cv-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio_cv-app

  template:
    metadata:
      labels:
        app: portfolio_cv-app
    spec:
      containers:
        - name: portfolio-cv-app
          image: portfolio_cv-app:latest
