import * as logoc from "./images/logo_cisco.png";
import * as logofreecodecamp from "./images/logo_freecodecamp.png";
import * as logogama from "./images/logo_gamasystem.png";
import * as logokomputronik from "./images/logo_komputronik.png";
import * as logomicrosoft from "./images/logo_microsoft.svg";
import * as logonbp from "./images/logo_nbp.jpg";
import * as logopsk from "./images/logo_psk.jpg";
import * as logoudemy from "./images/logo_udemy.png";
import * as logoujk from "./images/logo_ujk.png";
import * as logozsp from "./images/logo_zsp.jpg";
import * as exp from "./translations/pl/experience.json";
import * as edu from "./translations/pl/education.json";
import * as cert from "./translations/pl/certifications.json";
import * as proj from "./translations/pl/projects.json";
import * as sk from "./translations/pl/skills.json";
import * as globalpl from "./translations/pl/global.json";
import * as expen from "./translations/en/experience.json";
import * as eduen from "./translations/en/education.json";
import * as certen from "./translations/en/certifications.json";
import * as projen from "./translations/en/projects.json";
import * as skillsen from "./translations/en/skills.json";
import * as globalen from "./translations/en/global.json";
import * as flagpl from "./images/flag_pl.png";
import * as flaguk from "./images/flag_uk.png";
import * as cvpl from "./CV/CV_PL.pdf";
import * as cven from "./CV/CV_EN.pdf";

export const logoCisco = logoc.default;
export const logoFreecodecamp = logofreecodecamp.default;
export const logoGama = logogama.default;
export const logoKomputronik = logokomputronik.default;
export const logoMicrosoft = logomicrosoft.default;
export const logoNBP = logonbp.default;
export const logoPSK = logopsk.default;
export const logoUdemy = logoudemy.default;
export const logoUJK = logoujk.default;
export const logoZSP = logozsp.default;
export const experiences = exp;
export const education = edu;
export const certifications = cert;
export const projects = proj;
export const skills = sk;
export const global_pl = globalpl;
export const experiences_en = expen;
export const education_en = eduen;
export const certifications_en = certen;
export const projects_en = projen;
export const skills_en = skillsen;
export const global_en = globalen;
export const flag_pl = flagpl.default;
export const flag_uk = flaguk.default;
export const cv_pl = cvpl.default;
export const cv_en = cven.default;
